### ISSUE TITLE
Color code for labels

### ISSUE THREAD

**Issue by mforets** [JuliaReach/JuliaReachDevDocs#21]
Eg. #dbd851 for "meta" (taking as reference LazySets).

Table:

|Tag|Color|
|----|-----|
|meta|#dbd851|
|algorithm|#41ea2e|
|bug|#ee0701|
|discussion|#fbca04|
|performance|#428bca|

**Comment by schillic** [comment]
We can now [share labels for the whole organization](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-default-labels-for-repositories-in-your-organization) :tada:

**Comment by mforets** [comment]
That is a cool feature :tada:

**Comment by schillic** [comment]
I inserted the labels from `LazySets` [here](https://github.com/organizations/JuliaReach/settings/labels). They are now available for every new repository.

**Comment by mforets** [comment]
Excellent!
